language: python

python:
- "2.7"
- "3.3"

install:
- pip install codecov
- pip install coverage

script:
- python test.py
- coverage run test.py

after_success:
- codecov

deploy:
    provide: s3
    bucket:
    local-dir:
    region: